all: Assignment1.out

Assignment1.out: Assignment1.c  Assignment1functions.c Assignment1functions.h a1_defs.h
	gcc Assignment1.c Assignment1functions.c -o Assignment1.out 

clean:
	-rm Assignment1.out
